Added support for same region replicas.
cloudposse/terraform-aws-rds-replica pull request #3
Opened 2019-03-12 08:07 UTC by jstojanovski-scwx

Hi there... This fixes the fault I see with https://github.com/cloudposse/terraform-aws-rds-replica/issues/2

Be gentle- It's my first PR for a terraform module. :)

2019-03-14 03:18 UTC, aknysh commented
@jstojanovski-scwx  thanks!
please run `terraform fmt` on all files, CI/CD is failing

2019-03-14 03:35 UTC, aknysh commented on main.tf
> +  count                   = "${local.enabled && length(var.kms_key_id) == 0 && !var.same_region ? 1 : 0}"
```suggestion
  count                   = "${local.enabled && length(var.kms_key_id) == 0 && var.same_region == "false" ? 1 : 0}"
```

2019-03-14 03:35 UTC, aknysh commented on main.tf
> +  count      = "${local.enabled && !var.same_region ? 1 : 0}"
```suggestion
  count      = "${local.enabled && var.same_region == "false" ? 1 : 0}"
```

Since `var.same_region` is a string, not boolean

2019-03-14 03:43 UTC, aknysh requested changes
thanks @jstojanovski-scwx 
Looks good, just a few comments.
And after you address the comments, please run `terraform fmt` to format all TF files, and then rebuild README by executing these command:

```
make init
make readme/deps
make readme
```

This will add the new variable to `README.md`

2019-03-21 13:47 UTC, jwhitcraft commented
Any update on getting the suggestions fixed @jstojanovski-scwx  ?

If you don't have time, I can make the changes and push them to your branch.

2019-03-22 03:53 UTC, jstojanovski-scwx commented
@jwhitcraft Apologies... We stopped using this module, which meant it's fix priority dropped (for me). As a result, I haven't had the time to swing back around to fix it... If you have the cycles, please feel free. Otherwise, I'll get to it (just not for a while yet).

2019-03-22 19:05 UTC, closed without merging